### ISSUE TITLE
User Profile and Thread Settings

### ISSUE THREAD

**Issue by mrkrumhausen** [fbsamples/messenger-platform-samples#10]
This repo is very helpful! Would you mind adding User Profile and Thread Settings methods as well?

Thanks!

**Comment by jshin49** [comment]
@mrkrumhausen Hello. I made a Google Cloud Vision Bot referring to this sample a lot.
In my repository, I also have a file called 'threads.js', and I believe you can refer to this for Thread Settings.

https://github.com/jshin49/fb-vision-bot

**Comment by mrkrumhausen** [comment]
Thank you!

**Comment by mrkrumhausen** [comment]
Yup. My only issue is that I can't figure out how to save the result as a variable and preset single value back to the user, e.g. Hi firstname. 





On Thu, Jul 21, 2016 at 1:08 AM -0700, "Jay Shin" <notifications@github.com> wrote:












User Profile didn't seem difficult either.

Just send a request to the Graph API URL given in the Docs regarding User Profile, with the parameters as user id and page access token. 

The response will come as a User Profile JSON.

**Comment by jshin49** [comment]
Can you show me your code?

**Comment by mrkrumhausen** [comment]
```
getUserProfile (recipientId) {
  return request({
    method: 'GET',
    uri: 'https://graph.facebook.com/v2.6/${recipientId}',
    qs: {
      fields: 'first_name', //last_name,profile_pic,locale,timezone,gender
      access_token: process.env.FB_PAGE_ACCESS_TOKEN
    },
    json: true
  }, function(error, response, body) {
     userData = JSON.parse(body);
     console.log("GET USERDATA =" + JSON.stringify(userData));
     firstName = userData.first_name;
     //lastName = userData.last_name;
     return userData; //response.body;
  });
}
```

I'm also not sure when to actually call this method.

**Comment by jshin49** [comment]
Your code seems fine to call the user profile.

Just give a test run with it, by calling it with your userId or pageId as the recipientId.

```Javascript
function getUserProfile (recipientId) {
  var url = 'https://graph.facebook.com/v2.6/' + recipientId;
  return request({
    method: 'GET',
    uri: url,
    qs: {
      fields: 'first_name, last_name,profile_pic,locale,timezone,gender',
      access_token: PAGE_ACCESS_TOKEN
    }
  },
  function(error, response, body) {
    if (error) {
      console.error(error);
      return;
    }
    // console.log(body);
    var userData = JSON.parse(body);
    console.log(userData);
    return;
  });
}

getUserProfile(recipientId);
```

This code works for me.

**Comment by peter78** [comment]
Sure, I'll take note of adding these features in there.

**Comment by mrkrumhausen** [comment]
Thanks that would be great!
