### ISSUE TITLE
Unable to reach ec2 ip 

### ISSUE THREAD

**Issue by Snigdha29** [fbsamples/messenger-platform-samples#126]
I have created a webhook for messenger, and deployed to an ec2 instance, as outlined in:[https://developers.facebook.com/docs/messenger-platform/getting-started/webhook-setup](url)

While the below commands work with localhost, it doesn't when I try replacing localhost with the public ip of the ec2 instance.It says it refused to connect.

curl -X GET "localhost:1337/webhook?hub.verify_token=<YOUR_VERIFY_TOKEN>&hub.challenge=CHALLENGE_ACCEPTED&hub.mode=subscribe"

curl -H "Content-Type: application/json" -X POST "localhost:1337/webhook" -d '{"object": "page", "entry": [{"messaging": [{"message": "TEST_MESSAGE"}]}]}'

What am I missing here?

**Comment by PHUNGVULINH** [comment]
https://developers.facebook.com/docs/messenger-platform/getting-started/webhook-setup

**Comment by jorgeluiso** [comment]
the hub.challenge is typically a number set by FB servers and you need to reply that number in order to verify.
