### ISSUE TITLE
Can't get Handover sample "take from inbox" to work

### ISSUE THREAD

**Issue by jarrodeqtr** [fbsamples/messenger-platform-samples#129]
Hi, 

I'm using the  handover protocol sample and it's mostly working fine - I can pass to the inbox, and then the bot stops responding so the page inbox now handles the conversation. But, if I try the "take from inbox" action, it doesn't do anything because it doesn't seem to be hitting the webhook anymore (presumably because it is now pointing to the secondary app). I have put console logging in place which I can see for the "pass to inbox", and when the inbox is marked as done, but not for the take from inbox.

Any idea on what I might be doing wrong?

Thanks,
Jarrod

**Comment by jorgeluiso** [comment]
Two things worth mentioning that I thing will bring clarity.
1) Subscribe to the Standby Channel so your app sees conversions that are being handed over.
2) A request thread controller means the intent but the primary needs to pass the thread.
https://developers.facebook.com/docs/messenger-platform/handover-protocol/

**Comment by jarrodeqtr** [comment]
Thank you @jorgeluiso for pointing me in the right direction. It was the standby channel that I hadn't subscribed to. After I eventually found the webhooks setup, adding "standby" sorted it out for me.
