### ISSUE TITLE
Demo don't have https for default

### ISSUE THREAD

**Issue by ikarius6** [fbsamples/messenger-platform-samples#13]
Its hard to test the example when Facebook Webhook should be HTTPS, but this demo don't have optimization for HTTPS, so its impossible to test the initial demo.

**Comment by ikarius6** [comment]
Something like this...

```javascript
fs = require('fs');
...
//app.set('port', process.env.PORT || 5000);
...
var options = {
    key:    fs.readFileSync('/etc/ssl/private/site.key'),
    cert:   fs.readFileSync('/etc/ssl/certs/site.crt'),
    ca:     fs.readFileSync('/etc/ssl/certs/site.cer')
};
https.createServer(options, app).listen(5000, "0.0.0.0");
```

**Comment by julien-c** [comment]
Most people probably just host the demo app behind a reverse proxy server like `nginx` that does the SSL termination itself.

**Comment by peter78** [comment]
I'll consider adding this. I didn't want to go down the rabbit hole of handling https in this code as there are varying ways of handling it (e.g., certain hosting services handle this automagically).
