### ISSUE TITLE
how to include .env file ?

### ISSUE THREAD

**Issue by kamiliazainal** [fbsamples/messenger-platform-samples#133]
Hi, i'm trying to combine this handover protocol sample with my own bot, but i wanna test if it first. However, i keep on getting error cannot find module './env'. I deploy this in heroku. i'm very new with all this thing, so i might missed the step or anything. Can you help me ? Thank you

**Comment by jorgeluiso** [comment]
No problem happy to help, and thanks for reaching out. On Heroku you won't be using the .env file but rather Environmental Variables. I updated the guide to provide clarification, please let me know if this is helpful.

See the new Step 4 of the Using Heroku section.
https://developers.facebook.com/docs/messenger-platform/getting-started/sample-apps/original-coast-clothing#using-heroku

My suggestion is to complete the guide to have the Messenger App running and working on your server, from there edit code to test how things work. Then implement HOP to pass the thread to the page inbox. We need to add the Roadmap here for everyone to see but HOP will be implemented into the sample app before end of month.
