### ISSUE TITLE
Facebook Messenger Webhook cURL Post Error

### ISSUE THREAD

**Issue by ghhaider** [fbsamples/messenger-platform-samples#136]
This command giving the error:
curl -H "Content-Type: application/json" -X POST "localhost:1337/webhook" -d '{"object": "page", "entry": [{"messaging": [{"message": "TEST_MESSAGE"}]}]}'

Error:
![Capture](https://user-images.githubusercontent.com/52279553/63187271-df35d880-c077-11e9-8457-6e11c1b9cc65.PNG)

**Comment by jorgeluiso** [comment]
I don't understand what is this about. You are posting a made up web hook that does not have the same format into your app. How is this connected to the code?

you can trigger the send of mock webhooks from the app dashboard.

I suggest following this guide to test our platform
https://developers.facebook.com/docs/messenger-platform/getting-started/sample-apps/original-coast-clothing
