### ISSUE TITLE
Messengers 

### ISSUE THREAD

**Issue by Ches1422** [fbsamples/messenger-platform-samples#139]
[YouTubeAndroidPlayerApi-1.2.2.zip](https://github.com/fbsamples/messenger-platform-samples/files/4332727/YouTubeAndroidPlayerApi-1.2.2.zip)
[appauth-android-codelab-master.zip](https://github.com/fbsamples/messenger-platform-samples/files/4332728/appauth-android-codelab-master.zip)

_Originally posted by @Ches1422 in https://github.com/fbsamples/messenger-platform-samples/pull/128#issuecomment-599053686_

**Comment by jorgeluiso** [comment]
This is not related to this code, possibly malware. Reporting this
