### ISSUE TITLE
not receiving post on webhook for text messages

### ISSUE THREAD

**Issue by crosofg** [fbsamples/messenger-platform-samples#14]
I have checked messages option in webhooks. Still I am not receiving callback on webhooks for text messages. Although I get messaging_postback callbacks. What could be the issue?

**Comment by crosofg** [comment]
Closing. The page was somehow unsubscribed. That led to the issue.

**Comment by SzymonLisowiec** [comment]
The same problem, but I have subscribed messaging_postbacks.

**Comment by crosofg** [comment]
You need to subscribe to the page also

**Comment by SzymonLisowiec** [comment]
I have subscribed page (normally receiving messages).
