### ISSUE TITLE
No Such Branch As `tutorial-starters` As Mentioned In messenger-platform-samples/quick-start/README.md

### ISSUE THREAD

**Issue by Rubix982** [fbsamples/messenger-platform-samples#141]
Hello.

I was following the guide for setting up a quick messenger app using the Facebook's API at [Quick Start Tutorial](https://developers.facebook.com/docs/messenger-platform/getting-started/quick-start) which directed me to [Quick Start Tutorial - Finished Project](https://github.com/fbsamples/messenger-platform-samples/tree/master/quick-start) which has a README.md that says,
```
If you want to follow the quick start from scratch, download the starter code from the tutorial-starters branch of this repo.
```

Yet, there is no such branch on this repository,
![image](https://user-images.githubusercontent.com/41635766/80282940-b9e08a80-872d-11ea-8cd9-56c746a8ef0c.png)

Clicking on the link leads me to a github 404 page. Looking at the raw README.md, I found that the URL should redirect me to a page with the address `https://github.com/fbsamples/messenger-platform-samples/tree/tutorial-starters/quick-start`, also, it should be mentioned that the the 'Quick Start Tutorial - Finished Project` at `messenger-platform-samples/quick-start/` contains no instructions on how to actually run the `app.js` file - which is confusing for me since I'm not very familiar with how to modify the settings of the repository to make it work.

Any help would be appreciated and thanked for.

Have a nice day!

**Comment by Barbog** [comment]
Thanks for pointing that out. The ReadMe should now be updated.

**Comment by Rubix982** [comment]
I forgot about this issue's existence completely, but thanks, @Barbog !
