### ISSUE TITLE
How to send a document using this repo

### ISSUE THREAD

**Issue by hammadyounas2008** [fbsamples/messenger-platform-samples#155]
I have a document file I want to send through this repo how can I processed it?

**Comment by Ghaethliii** [comment]
https://github.com/googleads/googleads-mobile-android-mediation/blob/f23b1a236d4b59d84d5f747f4cb09d15ae648f79/CONTRIBUTING.md

**Comment by Ghaethliii** [comment]
https://github.com/googleads/googleads-mobile-android-mediation/blob/f23b1a236d4b59d84d5f747f4cb09d15ae648f79/CONTRIBUTING.md

**Comment by Ghaethliii** [comment]
Duplicate of #

**Comment by Barbog** [comment]
This repo does not demonstrate the sending of generic files. However, you can find some examples of sending image attachments in 
* `messenger-platform-samples/node/app.js` — from line 411

Check the docs in https://developers.facebook.com/docs/messenger-platform/send-messages#sending_attachments for more examples.
