### ISSUE TITLE
main

### ISSUE THREAD

**Issue by Ghaethliii** [fbsamples/messenger-platform-samples#157]
https://github.com/googleads/googleads-mobile-android-mediation/blob/f23b1a236d4b59d84d5f747f4cb09d15ae648f79/CONTRIBUTING.md

**Comment by Ghaethliii** [comment]
main

**Comment by Ghaethliii** [comment]
https://github.com/googleads/googleads-mobile-android-mediation/blob/f23b1a236d4b59d84d5f747f4cb09d15ae648f79/CONTRIBUTING.md

**Comment by Ghaethliii** [comment]
https://github.com/googleads/googleads-mobile-android-mediation/blob/f23b1a236d4b59d84d5f747f4cb09d15ae648f79/CONTRIBUTING.md

**Comment by Barbog** [comment]
No actionable information in this filed issue. 
Should there be something awry, please describe the issue in a new Issue.
