### ISSUE TITLE
Typescript typings and support

### ISSUE THREAD

**Issue by Coinhexa** [fbsamples/messenger-platform-samples#159]
Is there any way to get typescript typings or support or perhaps some TS examples?

**Comment by wanderingstan** [comment]
Thanks for your comment. We don't currently have Typescript examples but will make a note of your suggestion when developing future roadmaps.

**Comment by Coinhexa** [comment]
> Thanks for your comment. We don't currently have Typescript examples but will make a note of your suggestion when developing future roadmaps.

Ok but in my current project where I am developing stuff with Typescript, how do I get typings for the various message formats, attachments, messenger profile API etc?
