### ISSUE TITLE
Account Linking Failed

### ISSUE THREAD

**Issue by avenchen** [fbsamples/messenger-platform-samples#27]
I follow the steps to trigger /authorize, but I always got the facebook "Account Linking Failed" information.  What environment I need to check? Thanks

**Comment by kevinsimper** [comment]
Yes, got the same and it is not really clear why sadly :(

**Comment by kevinsimper** [comment]
Found the problem, I did not assign the `account_linking` permission in the dashboard 👍 

Thinks that solve it for you also @avenchen

**Comment by avenchen** [comment]
Thanks kevinsimper. After checking account_linking then work.
