### ISSUE TITLE
Getting down after starting the sample app.js

### ISSUE THREAD

**Issue by arshadpkm** [fbsamples/messenger-platform-samples#3]
After starting the app.js if I make a first request to the app it's getting down, 

I am using pm2 for starting node app, so in pm2 list command I can see the status of the app as errored.

**Comment by peter78** [comment]
Sorry, don't understand. Can you share more info?

**Comment by krishnakanthgupta** [comment]
what is validationtoken in default.json file?

In index.html its showing as data-ref="PASS_THROUGH_PARAM" what do u mean by it?

**Comment by arshadcodilar** [comment]
Issue solved after rebooting my server, Thank you.

**Comment by arshadpkm** [comment]
Issue solved after rebooting the server, Thank you.
