### ISSUE TITLE
No metadata field received in quick_reply action

### ISSUE THREAD

**Issue by trieudh58** [fbsamples/messenger-platform-samples#30]
I find this code in your sample:

```javascript
function sendQuickReply(recipientId) {
  ...
    message: {
      text: "What's your favorite movie genre?",
      metadata: "DEVELOPER_DEFINED_METADATA",
  ...
```
There is a field called "metadata" as a attribute of the **message** object, but when I read the [offical docs](https://developers.facebook.com/docs/messenger-platform/send-api-reference/quick-replies#fields), there's none.

I have tried it in my program too, and it did not work ([screenshot here](https://github.com/trieudh58/messenger-chatbot-guideline/blob/master/screenshots/no-metadata.png)). Please help me figure out what is true? Your code or the documentation?

**Comment by peter78** [comment]
The sample code is wrong. There's no metadata field for text messages. I'll update app.js.
