### ISSUE TITLE
Validation Failure

### ISSUE THREAD

**Issue by Tinyik** [fbsamples/messenger-platform-samples#33]
Hello. I'm new to node.js and Messenger Platform. Congrats on developing such a handy and lovely platform!

When trying out your official sample I'm running it at c9.io with node.js environment at URL https://xxx.c9users.io/webhook. I've filled in the blanks at default.json and index.html. When running with `npm start`, the c9 indicates the app starts correctly but Facebook always can't validate my URL.

_The URL couldn't be validated. Callback verification failed with the following errors: curl_errno = 47; curl_error = Maximum (2) redirects followed; HTTP Status Code = 302; HTTP Message = Moved Temporarily_

Could you please help me look into this problem?
Many thanks!

**Comment by Tinyik** [comment]
@peter78 @passy @jamesgpearce @vjeux @iamscott Thank you for helping me look into this issue!

**Comment by aldanchenko** [comment]
Sorry, but how you fix it?
