### ISSUE TITLE
Add webview and extensions sample

### ISSUE THREAD

**Issue by AdrianKrebs** [fbsamples/messenger-platform-samples#35]
Hei :)
How about adding a webview sample? I searched on GitHub but found no sample code of how to use it except the documentation. https://developers.facebook.com/docs/messenger-platform/send-api-reference/webview

**Comment by merlinvn** [comment]
Yeah, it's appear that I cannot use jquery and bootstrap for the webview, the items appear to be really small. What the best practices to layout items?

**Comment by peter78** [comment]
Yes, building in latest features. Will be out soon. :)

**Comment by commit-master** [comment]
Any update on this one ?

**Comment by cama** [comment]
Update?

**Comment by commit-master** [comment]
It is now out @cama you can find it here : https://github.com/fbsamples/messenger-bot-samples/tree/master/gui-webview
