### ISSUE TITLE
Broken link in README.md

### ISSUE THREAD

**Issue by Kulbear** [fbsamples/messenger-platform-samples#41]
Hi,
Just want to let you know that the link in README.md is broken now. Well it's not really broken but the post cannot be found anymore on the site.
This one:
https://developers.facebook.com/docs/messenger-platform/quickstart

**Comment by GongChuanZan** [comment]
Console 'Missing config values', How to config?

**Comment by Kulbear** [comment]
It seems that the link is fixed now.
