### ISSUE TITLE
How to send notifications to all users after pages_messaging_subscriptions approval?

### ISSUE THREAD

**Issue by devbikshu** [fbsamples/messenger-platform-samples#42]
Hi,

How to send notifications to all messenger Bot users?. Should I implement any logic for storing all subscribed users ID's and then send notifications (or) I can send notifications using my facebook page.

For my page **pages_messaging_subscriptions**  is Approved.

Thanks,

**Comment by BeautyPrincess** [comment]
://www.facebook.com/groups/xiagerkorea/
