### ISSUE TITLE
Failed at the messenger-get-started@1.0.0 start script 'node app.js'

### ISSUE THREAD

**Issue by Tom951** [fbsamples/messenger-platform-samples#43]
Hi,
When trying to run it, I have this error. Any clue?

npm start

> messenger-get-started@1.0.0 start /Users/TomJ/Documents/NODEJS
> node app.js

Missing config values

npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! messenger-get-started@1.0.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the messenger-get-started@1.0.0 start script 'node app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the messenger-get-started package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs messenger-get-started
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls messenger-get-started
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/TomJ/Documents/NODEJS/npm-debug.log

**Comment by jmartinm** [comment]
> Missing config values

It means you have to fill the configuration in:

https://github.com/fbsamples/messenger-platform-samples/blob/master/node/config/default.json

**Comment by Tom951** [comment]
My bad! Thanks a lot.

**Comment by martin0852** [comment]
I'm here from a blank slate POV can I just fill in any jobberish or do I need to set up a server first? Sorry for new question but I'm literally starting form scratch here

**Comment by ishandutta2007** [comment]
The problem still persits for me after deploying to ec2 http://stackoverflow.com/questions/42848992/failed-at-the-messenger-get-started1-0-0-start-script-node-app-js
