### ISSUE TITLE
Complete newbie

### ISSUE THREAD

**Issue by molverat** [fbsamples/messenger-platform-samples#52]
Hello community. 

I am trying to create a bot. Using this project. My setup is as follows: 

Amazon EC2 instance. I created a sub-domain.domain.com I have added the ssl certifications. I have pointed the sub-domain to the /var/www/sub-domain/  I have installed the unzip and installed the project in /var/www/sub-domain/project/ I have configured the project and correctly run it: 

Node app is running on port 5000
If i access http://sub-domain.domain.com:5000 I access to the projects public index.  I understand that means the port is open and the node app works.

Now when I am trying to configure in facebook my webhook I dont understand what url  callbak to use. From what I understand in the configuration the server url whould be https://sub-domain.domain.com and the configuration should work. but it doesnt.

What url should I use?

**Comment by peter78** [comment]
This isn't the correct place to get help. Please try StackOverflow.
