### ISSUE TITLE
make it possible to install npm from git

### ISSUE THREAD

**Issue by TrejGun** [fbsamples/messenger-platform-samples#54]
like this

package.json

```
...
  "devDependencies": {
...
    "messenger-get-started": "git://github.com/fbsamples/messenger-platform-samples.git#HASH",
...
  }
...
```

please :)

**Comment by peter78** [comment]
Issues aren't a place to ask questions. Please use something like Stackoverflow.

**Comment by TrejGun** [comment]
@peter78 this is not a question
npm requires package.json in the repository root to be able to install directly from git
