### ISSUE TITLE
Stop FB app from trying to send message to server

### ISSUE THREAD

**Issue by trieudh58** [fbsamples/messenger-platform-samples#57]
Hi. My problem is that I need to stop facebook app from trying to send message data to my server.

Is there any ways to notify facebook app that "I don't want to process that message, please don't trying to send me that again and again?"

How can I do this in `verifyRequestSignature` function? I'm thinking of sending a status code to facebook but I can't figure out what to send.

Thanks in advance!

**Comment by peter78** [comment]
Issues aren't a place to ask questions. Please use something like Stackoverflow.
