### ISSUE TITLE
Is there any Facebook bot framework like MSBot builder ?

### ISSUE THREAD

**Issue by deepakmhr** [fbsamples/messenger-platform-samples#59]
Has Facebook launches any bot builder framework ?

**Comment by hayeuanh1986** [comment]
has

**Comment by hayeuanh1986** [comment]
[](https://developers.facebook.com/docs/messenger-platform/guides/quick-start/)

**Comment by johnotu** [comment]
No there isn't a library or framework for Facebook bots like the MSBot builder. Facebook uses SEND/RECEIVE API calls as building block for their bots and everything you need to do can be done with those APIs. See the [documentation](https://developers.facebook.com/docs/messenger-platform) for details.

**Comment by peter78** [comment]
Issues aren't a place to ask questions. Please use something like Stackoverflow.
