### ISSUE TITLE
Webhook post error

### ISSUE THREAD

**Issue by samko635** [fbsamples/messenger-platform-samples#73]
Hi, I did everything as instructions(https://developers.facebook.com/docs/messenger-platform/getting-started/webhook-setup) but I keep getting this error! 
What did I do wrong?

Requesting side>>>

curl -H "Content-Type:application/json" -X POST "localhost:1337/webhook" -d '{"object": "page", "entry": [{"messaging": [{"message": "TEST_MESSAGE"}]}]}'
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>SyntaxError: Unexpected token # in JSON at position 0<br> &nbsp; &nbsp;at JSON.parse (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at createStrictSyntaxError (C:\Users\yshvc\messenger-webhook\node_modules\body-parser\lib\types\json.js:157:10)<br> &nbsp; &nbsp;at parse (C:\Users\yshvc\messenger-webhook\node_modules\body-parser\lib\types\json.js:83:15)<br> &nbsp; &nbsp;at C:\Users\yshvc\messenger-webhook\node_modules\body-parser\lib\read.js:121:18<br> &nbsp; &nbsp;at invokeCallback (C:\Users\yshvc\messenger-webhook\node_modules\raw-body\index.js:224:16)<br> &nbsp; &nbsp;at done (C:\Users\yshvc\messenger-webhook\node_modules\raw-body\index.js:213:7)<br> &nbsp; &nbsp;at IncomingMessage.onEnd (C:\Users\yshvc\messenger-webhook\node_modules\raw-body\index.js:273:7)<br> &nbsp; &nbsp;at emitNone (events.js:106:13)<br> &nbsp; &nbsp;at IncomingMessage.emit (events.js:208:7)<br> &nbsp; &nbsp;at endReadableNT (_stream_readable.js:1056:12)</pre>
</body>
</html>
curl: (6) Couldn't resolve host 'page,'
curl: (6) Couldn't resolve host 'entry'
curl: (3) [globbing] bad range specification in column 2
curl: (3) [globbing] bad range specification in column 2
curl: (3) [globbing] unmatched close brace/bracket in column 13

=====================================================

Node side>>>

SyntaxError: Unexpected token # in JSON at position 0
    at JSON.parse (<anonymous>)
    at createStrictSyntaxError (C:\Users\yshvc\messenger-webhook\node_modules\body-parser\lib\types\json.js:157:10)
    at parse (C:\Users\yshvc\messenger-webhook\node_modules\body-parser\lib\types\json.js:83:15)
    at C:\Users\yshvc\messenger-webhook\node_modules\body-parser\lib\read.js:121:18
    at invokeCallback (C:\Users\yshvc\messenger-webhook\node_modules\raw-body\index.js:224:16)
    at done (C:\Users\yshvc\messenger-webhook\node_modules\raw-body\index.js:213:7)
    at IncomingMessage.onEnd (C:\Users\yshvc\messenger-webhook\node_modules\raw-body\index.js:273:7)
    at emitNone (events.js:106:13)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)

**Comment by amuramoto** [comment]
Can you post a gist or link to your code? It appears you probably have a syntax error in your index.js file.

**Comment by samko635** [comment]
https://gist.github.com/samko635/223521633a4a317c2a5bc4c6f110d376
These are the files I created following the manual. And there is node_modules directory created by Node.js promt with npm command. What is wrong with this?

**Comment by amuramoto** [comment]
What version of node are you running? I've run the code and the cURL request you provided and did not get an error.

**Comment by amuramoto** [comment]
Closing this since there has been no response for over a week.

**Comment by ladiesman1792** [comment]
I'm also getting this issue! Please help!

**Comment by marketingstarz** [comment]
also getting same error. any chance to reopen?

**Comment by vojtob** [comment]
I am using curl on cmder and this command works fine:
curl -H "Content-Type: application/json" -X POST "localhost:1337/webhook" -d {\"object\":\"page\",\"entry\":[{\"messaging\":[{\"message\":\"TEST_MESSAGE\"}]}]}

**Comment by JHero23** [comment]
I've been having the exact same problem, i tried on the command line tool, but i still can't figure out what the problem is.

**Comment by NobleAscent** [comment]
I was just having the same error and tried to use the version of @vojtob it started worked!
Magic
