### ISSUE TITLE
Port to scala

### ISSUE THREAD

**Issue by diwalak** [fbsamples/messenger-platform-samples#9]
Would you be willing to accept a port of the samples to scala ? 

I would base it on either play-framework or akka-http.

**Comment by patrickprincivil** [comment]
Yes

**Comment by peter78** [comment]
Hmm maybe not for now as part of the official repo. But if it is fully featured and of a certain quality I'll consider pointing to it as an unofficial version from the README.

**Comment by patrickprincivil** [comment]
Hey,

I just signed the petition "Jovenel Moise: POUR UN PROCES PETROCARIBE"
and wanted to see if you could help by adding your name.

Our goal is to reach 12,220 signatures and we need more support. You
can read more and sign the petition here:

https://chn.ge/2PhdfdE

Thanks!
Patrick
